### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Prosta4okua** [16Bogdan54/guessAge-bot-NodeJS#1]
капець, чому нічо не працює

**Comment by 16Bogdan54** [comment]
Currently, it doesn't work since I've been working on this project this
week. I have no clue how telegram API works, so I need to make sure that I
know exactly what I do.

**Comment by Prosta4okua** [comment]
use chatgpt lol

вт, 10 січ. 2023, 19:53 користувач Bohdan Yunakov ***@***.***>
пише:
